# Generated by Django 3.1.7 on 2021-04-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=16)),
                ('jurusan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_request', models.CharField(max_length=100)),
                ('image_result', models.CharField(max_length=100)),
                ('user_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognation.usertarget')),
            ],
        ),
    ]
