# Generated by Django 3.1.7 on 2021-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognation', '0003_auto_20210428_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
