# Generated by Django 3.1.7 on 2021-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognation', '0004_transaction_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image_recog',
            field=models.CharField(default='person.png', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image_result',
            field=models.CharField(max_length=150),
        ),
    ]
