# Generated by Django 3.1.7 on 2021-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognation', '0005_auto_20210428_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_target',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_predicted',
            field=models.IntegerField(default=0),
        ),
    ]
